# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Static Content to Azure Web App - amaflix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_static: # Simplified job name, as no 'build' is needed for static files
    runs-on: windows-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3E61B0A7378A4E01A11C09CDBF190B09 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADA7FF960B0E43479217D8A850754FE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4BB8A55E27494E99B66C9CF95E822E47 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amaflix'
          slot-name: 'Production'
          # 'package: .' tells the action to deploy everything from the root of your repo directly
          package: .


